version: '3'

tasks:
  make:
    desc: Install monaco-editor and analyze the module dependency
    cmds:
      - pnpm i
      - rm -rf monaco-editor lib
      - cp -R -L node_modules/monaco-editor .
      - mv monaco-editor lib
      - rm -rf lib/node_modules lib/min lib/dev
      - rm -f
          lib/package.json
          lib/esm/vs/editor/editor.all.js
          lib/monaco.d.ts
          lib/esm/vs/editor/internal/initialize.d.ts
      - task: analyze

  analyze:
    - bun src/analyze.ts

  dev:
    - shwoop src --host

