version: '3'


tasks:
  upgrade:
    - >
      pnpm up -r mono-dev @pistonite/pure @pistonite/celera @catppuccin/palette
      @types/react @types/node
      es-module-lexer
    - pnpm dedupe
    - pnpm dedupe --check
