// generated by AI

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { resolve, relative, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { init, parse } from "es-module-lexer";

const __dirname = dirname(dirname(fileURLToPath(import.meta.url)));
const ESM_DIR = resolve(__dirname, "lib", "esm");
const EXTERNAL_DIR = resolve(ESM_DIR, "external");
const OUTPUT_FILE = join(__dirname, "src", "dependency.json");

function walkDir(dir: string): string[] {
    const files: string[] = [];
    for (const entry of readdirSync(dir)) {
        const fullPath = join(dir, entry);
        if (statSync(fullPath).isDirectory()) {
            if (fullPath === EXTERNAL_DIR) continue;
            files.push(...walkDir(fullPath));
        } else if (entry.endsWith(".js")) {
            files.push(fullPath);
        }
    }
    return files;
}

function getLineNumber(source: string, pos: number): number {
    let line = 1;
    for (let i = 0; i < pos; i++) {
        if (source[i] === "\n") line++;
    }
    return line;
}

await init;

// ── Step 1: collect per-file deps ─────────────────────────────────────────────

const allFiles = walkDir(ESM_DIR);
console.log(`Found ${allFiles.length} .js files`);

const deps: Record<string, string[]> = {};

for (const filePath of allFiles) {
    const relFile = relative(ESM_DIR, filePath).replace(/\\/g, "/");
    const source = readFileSync(filePath, "utf-8");
    const fileDir = dirname(filePath);

    let imports: ReturnType<typeof parse>[0];
    try {
        [imports] = parse(source);
    } catch {
        console.warn(`[WARN] Failed to parse: ${relFile}`);
        deps[relFile] = [];
        continue;
    }

    const fileDeps: string[] = [];
    for (const imp of imports) {
        if (imp.d >= 0) {
            if (imp.n) {
                if (imp.n.startsWith(".")) {
                    const rel = relative(ESM_DIR, resolve(fileDir, imp.n)).replace(/\\/g, "/");
                    if (!rel.startsWith("..") && !rel.startsWith("external/")) fileDeps.push(rel);
                }
            } else {
                const line = getLineNumber(source, imp.s);
                const snippet = source.slice(imp.s, imp.e).slice(0, 80);
                console.warn(`[WARN] Dynamic import at ${relFile}:${line} — ${snippet}`);
            }
        } else {
            if (imp.n && imp.n.startsWith(".")) {
                const rel = relative(ESM_DIR, resolve(fileDir, imp.n)).replace(/\\/g, "/");
                if (!rel.startsWith("..") && !rel.startsWith("external/")) fileDeps.push(rel);
            }
        }
    }
    deps[relFile] = [...new Set(fileDeps)];
}

// ── Step 2: Kosaraju's SCC ────────────────────────────────────────────────────

// Filter deps to only reference files we actually walked (drop broken imports)
const fileSet = new Set(Object.keys(deps));
for (const [file, imports] of Object.entries(deps)) {
    const filtered = imports.filter(imp => fileSet.has(imp));
    if (filtered.length !== imports.length) {
        const missing = imports.filter(imp => !fileSet.has(imp));
        for (const m of missing) console.warn(`[WARN] Missing file: ${m} (imported by ${file})`);
    }
    deps[file] = filtered;
}

const fileList = Object.keys(deps);

// Build in-edges (reversed graph)
const inEdges = new Map<string, string[]>(fileList.map(f => [f, []]));
for (const [file, imports] of Object.entries(deps)) {
    for (const imp of imports) {
        inEdges.get(imp)?.push(file);
    }
}

// DFS pass 1: record finish order on original graph
const visited1 = new Set<string>();
const finishOrder: string[] = [];

function dfs1(start: string) {
    const stack: [string, number][] = [[start, 0]];
    visited1.add(start);
    while (stack.length > 0) {
        const frame = stack[stack.length - 1];
        const neighbors = deps[frame[0]] ?? [];
        if (frame[1] < neighbors.length) {
            const next = neighbors[frame[1]++];
            if (!visited1.has(next)) {
                visited1.add(next);
                stack.push([next, 0]);
            }
        } else {
            stack.pop();
            finishOrder.push(frame[0]);
        }
    }
}

for (const f of fileList) {
    if (!visited1.has(f)) dfs1(f);
}

// DFS pass 2: reverse finish order on reversed graph → SCCs
const visited2 = new Set<string>();
const sccs: string[][] = [];

for (let i = finishOrder.length - 1; i >= 0; i--) {
    const start = finishOrder[i];
    if (visited2.has(start)) continue;
    const scc: string[] = [];
    const stack = [start];
    visited2.add(start);
    while (stack.length > 0) {
        const node = stack.pop()!;
        scc.push(node);
        for (const imp of inEdges.get(node) ?? []) {
            if (!visited2.has(imp)) {
                visited2.add(imp);
                stack.push(imp);
            }
        }
    }
    sccs.push(scc);
}

// ── Step 3: build condensed group DAG ─────────────────────────────────────────

const fileToGroup = new Map<string, number>();
sccs.forEach((scc, i) => scc.forEach(f => fileToGroup.set(f, i)));

const groupDepsSet = sccs.map(() => new Set<number>());
for (const [file, imports] of Object.entries(deps)) {
    const gFrom = fileToGroup.get(file)!;
    for (const imp of imports) {
        const gTo = fileToGroup.get(imp);
        if (gTo !== undefined && gTo !== gFrom) groupDepsSet[gFrom].add(gTo);
    }
}

const output = sccs.map((files, i) => ({
    files,
    deps: [...groupDepsSet[i]],
}));

writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2));

const nonSingletons = sccs.filter(s => s.length > 1);
console.log(`\nWrote ${sccs.length} groups to ${OUTPUT_FILE}`);
console.log(`Non-singleton groups: ${nonSingletons.length}`);
if (nonSingletons.length > 0) {
    console.log("Largest groups:");
    nonSingletons.sort((a, b) => b.length - a.length).slice(0, 5).forEach(g => {
        console.log(`  ${g.length} files: ${g[0]}`);
    });
}
