// generated by AI

const H_GAP     = 10;
const V_GAP     = 44;
const TOP_MARGIN  = 40;
const SIDE_MARGIN = 30;
const TAB_H     = 38;

const COLOR_MAP = [
    { prefix: "vs/base",            color: "#89b4fa", label: "vs/base" },
    { prefix: "vs/editor",          color: "#a6e3a1", label: "vs/editor" },
    { prefix: "vs/platform",        color: "#f9e2af", label: "vs/platform" },
    { prefix: "vs/basic-languages", color: "#cba6f7", label: "vs/basic-languages" },
    { prefix: "vs/language",        color: "#fab387", label: "vs/language" },
];
const COLOR_DEFAULT = "#cdd6f4";

// ── Load data ─────────────────────────────────────────────────────────────────

const groups = await fetch("dependency.json").then(r => r.json());

const outEdges = groups.map(g => new Set(g.deps));
const inEdges  = groups.map(() => new Set());
groups.forEach((g, i) => { for (const dep of g.deps) inEdges[dep].add(i); });

// ── Node helpers ──────────────────────────────────────────────────────────────

function nodeSize(g) {
    const n = groups[g].files.length;
    return Math.max(8, Math.min(Math.ceil(Math.sqrt(n) * 5), 50));
}

function nodeColor(g) {
    const files = groups[g].files;
    const counts = new Map();
    for (const f of files) {
        for (const { prefix, color } of COLOR_MAP) {
            if (f.startsWith(prefix)) { counts.set(color, (counts.get(color) || 0) + 1); break; }
        }
    }
    if (!counts.size) return COLOR_DEFAULT;
    let best = COLOR_DEFAULT, bestN = 0;
    for (const [c, n] of counts) { if (n > bestN) { best = c; bestN = n; } }
    return best;
}

// ── Transitive traversal ──────────────────────────────────────────────────────

function transitiveDeps(g) {
    const visited = new Set();
    const q = [...outEdges[g]];
    while (q.length) {
        const n = q.pop();
        if (visited.has(n)) continue;
        visited.add(n);
        for (const dep of outEdges[n]) if (!visited.has(dep)) q.push(dep);
    }
    return visited;
}

function transitiveImporters(g) {
    const visited = new Set();
    const q = [...inEdges[g]];
    while (q.length) {
        const n = q.pop();
        if (visited.has(n)) continue;
        visited.add(n);
        for (const imp of inEdges[n]) if (!visited.has(imp)) q.push(imp);
    }
    return visited;
}

// ── Connected components ──────────────────────────────────────────────────────

function findComponents() {
    const visited = new Set();
    const result  = [];
    for (let start = 0; start < groups.length; start++) {
        if (visited.has(start)) continue;
        const comp = new Set();
        const q    = [start];
        while (q.length) {
            const g = q.pop();
            if (visited.has(g)) continue;
            visited.add(g); comp.add(g);
            for (const nb of outEdges[g]) if (!visited.has(nb)) q.push(nb);
            for (const nb of inEdges[g])  if (!visited.has(nb)) q.push(nb);
        }
        result.push(comp);
    }
    return result.sort((a, b) => {
        const fa = [...a].reduce((s, g) => s + groups[g].files.length, 0);
        const fb = [...b].reduce((s, g) => s + groups[g].files.length, 0);
        return fb - fa;
    });
}

const components = findComponents();

// ── Layout: barycentric bottom-up ─────────────────────────────────────────────
//
// Each node is positioned at the horizontal center of its dependencies
// (the files it imports). Processed bottom-up so dependency positions
// are known before the importer is placed. Greedy left-to-right conflict
// resolution ensures no overlaps.

function computeLayout(compSet) {
    // Kahn's topological sort → levels
    const inDeg = new Map();
    for (const g of compSet) {
        let d = 0;
        for (const imp of inEdges[g]) { if (compSet.has(imp)) d++; }
        inDeg.set(g, d);
    }
    const level = new Map();
    const queue = [];
    for (const g of compSet) { if (!inDeg.get(g)) { level.set(g, 0); queue.push(g); } }
    let qi = 0;
    while (qi < queue.length) {
        const g = queue[qi++], l = level.get(g);
        for (const dep of outEdges[g]) {
            if (!compSet.has(dep)) continue;
            const nl = l + 1;
            if (!level.has(dep) || level.get(dep) < nl) level.set(dep, nl);
            const d = inDeg.get(dep) - 1;
            inDeg.set(dep, d);
            if (!d) queue.push(dep);
        }
    }
    let maxLevel = 0;
    for (const l of level.values()) if (l > maxLevel) maxLevel = l;
    for (const g of compSet) { if (!level.has(g)) level.set(g, maxLevel + 1); }
    const totalLevels = maxLevel + 2;

    const levelGroups = Array.from({ length: totalLevels }, () => []);
    for (const g of compSet) levelGroups[level.get(g)].push(g);

    const nodeX = new Map();
    const nodeY = new Map();

    // Bottom-up: position each node at the center-of-mass of its dependencies
    for (let li = totalLevels - 1; li >= 0; li--) {
        const row = levelGroups[li];

        // Compute each node's preferred center-X from its dependencies
        const preferred = new Map();
        for (const g of row) {
            const deps = [...outEdges[g]].filter(d => compSet.has(d) && nodeX.has(d));
            if (deps.length) {
                const cx = deps.reduce((s, d) => s + nodeX.get(d) + nodeSize(d) / 2, 0) / deps.length;
                preferred.set(g, cx - nodeSize(g) / 2);
            }
        }

        // Sort by preferred X so the greedy pass respects the desired order
        row.sort((a, b) => {
            const pa = preferred.has(a) ? preferred.get(a) : Infinity;
            const pb = preferred.has(b) ? preferred.get(b) : Infinity;
            return pa - pb;
        });

        // Greedy left-to-right: place each node at max(cursor, preferred)
        let cursor = 0;
        for (const g of row) {
            const s    = nodeSize(g);
            const pref = preferred.get(g);
            const x    = pref != null ? Math.max(cursor, pref) : cursor;
            nodeX.set(g, x);
            cursor = x + s + H_GAP;
        }
    }

    // Normalize so leftmost node starts at SIDE_MARGIN
    let minX = Infinity;
    for (const x of nodeX.values()) if (x < minX) minX = x;
    const shift = SIDE_MARGIN - minX;
    for (const g of compSet) nodeX.set(g, nodeX.get(g) + shift);

    // Compute row heights (max node size per level)
    const rowHeights = levelGroups.map(row => row.reduce((h, g) => Math.max(h, nodeSize(g)), 0));

    // Assign Y positions
    let y = TOP_MARGIN;
    for (let li = 0; li < totalLevels; li++) {
        for (const g of levelGroups[li]) nodeY.set(g, y);
        y += rowHeights[li] + V_GAP;
    }
    const canvasH = y + TOP_MARGIN - V_GAP;

    // Canvas width = max right edge + margin
    let maxRight = 0;
    for (const g of compSet) { const r = nodeX.get(g) + nodeSize(g); if (r > maxRight) maxRight = r; }
    const canvasW = maxRight + SIDE_MARGIN;

    return { level, levelGroups, rowHeights, nodeX, nodeY, canvasW, canvasH, totalLevels, nodes: [...compSet] };
}

const layoutCache = new Array(components.length).fill(null);
function getLayout(i) {
    if (!layoutCache[i]) layoutCache[i] = computeLayout(components[i]);
    return layoutCache[i];
}

// ── Canvas & transform ────────────────────────────────────────────────────────

const canvas = document.getElementById("canvas");
const ctx    = canvas.getContext("2d");

function viewH() { return window.innerHeight - TAB_H; }

const transform = { x: 0, y: 0, scale: 1 };
let highlighted = null; // { g, importers: Set<number>, dependencies: Set<number> }
let currentIdx  = 0;

function resetTransform(layout) {
    const vw = window.innerWidth, vh = viewH();
    transform.scale = Math.min(1, vw / layout.canvasW, vh / layout.canvasH);
    transform.x = (vw - layout.canvasW * transform.scale) / 2;
    transform.y = 20;
}

function screenToWorld(sx, sy) {
    return {
        x: (sx - transform.x) / transform.scale,
        y: (sy - TAB_H - transform.y) / transform.scale,
    };
}

function isVisible(wx, wy, w, h) {
    const sx = wx * transform.scale + transform.x;
    const sy = wy * transform.scale + transform.y;
    return sx + w * transform.scale > 0 && sx < window.innerWidth &&
           sy + h * transform.scale > 0 && sy < viewH();
}

// ── Render ────────────────────────────────────────────────────────────────────

function render() {
    const layout = getLayout(currentIdx);
    const { level, levelGroups, rowHeights, nodeX, nodeY, totalLevels, nodes } = layout;

    const dpr = window.devicePixelRatio || 1;
    canvas.width  = window.innerWidth * dpr;
    canvas.height = viewH() * dpr;

    ctx.setTransform(transform.scale * dpr, 0, 0, transform.scale * dpr,
                     transform.x * dpr, transform.y * dpr);
    const wx0 = -transform.x / transform.scale;
    const wy0 = -transform.y / transform.scale;
    ctx.clearRect(wx0, wy0, window.innerWidth / transform.scale, viewH() / transform.scale);

    // ── Edges ──
    if (highlighted) {
        const { g: hg, importers, dependencies } = highlighted;

        // All edges dimmed
        ctx.strokeStyle = "#45475a";
        ctx.lineWidth   = 0.5 / transform.scale;
        ctx.globalAlpha = 0.06;
        for (const n of nodes) {
            const x1 = nodeX.get(n) + nodeSize(n) / 2;
            const y1 = nodeY.get(n) + nodeSize(n);
            for (const dep of outEdges[n]) {
                if (!nodeX.has(dep)) continue;
                const x2 = nodeX.get(dep) + nodeSize(dep) / 2, y2 = nodeY.get(dep);
                if (!isVisible(Math.min(x1,x2), Math.min(y1,y2), Math.abs(x2-x1)||1, Math.abs(y2-y1)||1)) continue;
                ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke();
            }
        }

        // Highlighted edges: importer chain (orange) and dependency chain (green)
        ctx.lineWidth   = 1.2 / transform.scale;
        ctx.globalAlpha = 0.85;
        for (const n of nodes) {
            const nIsImp = importers.has(n);
            const nIsDep = dependencies.has(n);
            if (!nIsImp && !nIsDep && n !== hg) continue;

            const x1 = nodeX.get(n) + nodeSize(n) / 2;
            const y1 = nodeY.get(n) + nodeSize(n);

            for (const dep of outEdges[n]) {
                if (!nodeX.has(dep)) continue;

                // Edge n → dep:
                // orange if n ∈ importers and dep ∈ importers∪{hg}
                // green  if n ∈ {hg}∪dependencies and dep ∈ dependencies
                let color = null;
                if (nIsImp && (importers.has(dep) || dep === hg)) color = "#fab387";
                else if ((n === hg || nIsDep) && dependencies.has(dep))   color = "#a6e3a1";
                if (!color) continue;

                ctx.strokeStyle = color;
                const x2 = nodeX.get(dep) + nodeSize(dep) / 2, y2 = nodeY.get(dep);
                ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke();
            }
        }
        ctx.globalAlpha = 1;
    } else {
        ctx.strokeStyle = "#45475a";
        ctx.lineWidth   = 0.5 / transform.scale;
        ctx.globalAlpha = 0.35;
        for (const n of nodes) {
            const x1 = nodeX.get(n) + nodeSize(n) / 2;
            const y1 = nodeY.get(n) + nodeSize(n);
            for (const dep of outEdges[n]) {
                if (!nodeX.has(dep)) continue;
                const x2 = nodeX.get(dep) + nodeSize(dep) / 2, y2 = nodeY.get(dep);
                if (!isVisible(Math.min(x1,x2), Math.min(y1,y2), Math.abs(x2-x1)||1, Math.abs(y2-y1)||1)) continue;
                ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke();
            }
        }
        ctx.globalAlpha = 1;
    }

    // ── Nodes ──
    for (const n of nodes) {
        const x = nodeX.get(n), y = nodeY.get(n), s = nodeSize(n);
        if (!isVisible(x, y, s, s)) continue;

        if (highlighted) {
            const { g: hg, importers, dependencies } = highlighted;
            if (n === hg) {
                ctx.fillStyle = "#f5c2e7"; ctx.globalAlpha = 1;
            } else if (importers.has(n)) {
                ctx.fillStyle = "#fab387"; ctx.globalAlpha = 1;
            } else if (dependencies.has(n)) {
                ctx.fillStyle = "#a6e3a1"; ctx.globalAlpha = 1;
            } else {
                ctx.fillStyle = nodeColor(n); ctx.globalAlpha = 0.15;
            }
        } else {
            ctx.fillStyle = nodeColor(n); ctx.globalAlpha = 1;
        }
        ctx.fillRect(x, y, s, s);
    }

    // ── Side-effects outlines (drawn after nodes so they're always fully opaque) ──
    ctx.globalAlpha = 1;
    ctx.strokeStyle = "#f38ba8";
    for (const n of nodes) {
        if (!groups[n].sideEffects) continue;
        const x = nodeX.get(n), y = nodeY.get(n), s = nodeSize(n);
        if (!isVisible(x, y, s, s)) continue;
        ctx.lineWidth = Math.max(2, s * 0.15) / transform.scale;
        ctx.strokeRect(x, y, s, s);
    }
    ctx.globalAlpha = 1;

    // ── Level labels ──
    if (transform.scale > 0.3) {
        ctx.globalAlpha = 0.4;
        ctx.fillStyle   = "#6c7086";
        ctx.font        = `${10 / transform.scale}px monospace`;
        ctx.textAlign   = "left";
        const lx = wx0 + 4 / transform.scale;
        let ly = TOP_MARGIN;
        for (let li = 0; li < totalLevels; li++) {
            if (isVisible(wx0, ly, 1, rowHeights[li])) {
                ctx.fillText(`L${li} (${levelGroups[li].length})`, lx, ly + rowHeights[li] / 2 + 3 / transform.scale);
            }
            ly += rowHeights[li] + V_GAP;
        }
        ctx.globalAlpha = 1;
    }
}

// ── Tabs ──────────────────────────────────────────────────────────────────────

function tabLabel(comp, idx) {
    const totalFiles = [...comp].reduce((s, g) => s + groups[g].files.length, 0);
    if (idx === 0) return `Main (${totalFiles}f / ${comp.size}g)`;
    if (comp.size === 1) return groups[[...comp][0]].files[0].split("/").pop();
    const roots = [...comp].filter(g => ![...inEdges[g]].some(i => comp.has(i)));
    const name  = roots.length ? groups[roots[0]].files[0].split("/").pop().replace(/\.js$/, "") : "?";
    return `${name}… (${totalFiles})`;
}

function buildTabs() {
    const bar = document.getElementById("tabbar");
    bar.innerHTML = "";
    components.forEach((comp, i) => {
        const btn = document.createElement("button");
        btn.className = "tab" + (i === currentIdx ? " active" : "");
        btn.textContent = tabLabel(comp, i);
        const roots = [...comp].filter(g => ![...inEdges[g]].some(imp => comp.has(imp)));
        btn.title = roots.slice(0, 5).flatMap(g => groups[g].files).join("\n");
        btn.addEventListener("click", () => {
            if (i === currentIdx) return;
            currentIdx = i; highlighted = null;
            resetTransform(getLayout(i));
            buildTabs(); render();
        });
        bar.append(btn);
    });
}

// ── Interaction ───────────────────────────────────────────────────────────────

function hitTest(sx, sy) {
    const { nodeX, nodeY, nodes } = getLayout(currentIdx);
    const { x: wx, y: wy } = screenToWorld(sx, sy);
    for (const g of nodes) {
        const nx = nodeX.get(g), ny = nodeY.get(g), ns = nodeSize(g);
        if (wx >= nx && wx <= nx + ns && wy >= ny && wy <= ny + ns) return g;
    }
    return null;
}

let panning = false, didPan = false;
let panStart = { x: 0, y: 0, tx: 0, ty: 0 };

canvas.addEventListener("mousedown", e => {
    panning = true; didPan = false;
    panStart = { x: e.clientX, y: e.clientY, tx: transform.x, ty: transform.y };
    canvas.classList.add("panning");
});
window.addEventListener("mousemove", e => {
    if (!panning) return;
    const dx = e.clientX - panStart.x, dy = e.clientY - panStart.y;
    if (Math.abs(dx) > 2 || Math.abs(dy) > 2) didPan = true;
    transform.x = panStart.tx + dx; transform.y = panStart.ty + dy;
    render();
});
window.addEventListener("mouseup", () => { panning = false; canvas.classList.remove("panning"); });

canvas.addEventListener("wheel", e => {
    e.preventDefault();
    const factor = e.deltaY < 0 ? 1.1 : 1 / 1.1;
    const mx = e.clientX, my = e.clientY - TAB_H;
    transform.x = mx - (mx - transform.x) * factor;
    transform.y = my - (my - transform.y) * factor;
    transform.scale *= factor;
    render();
}, { passive: false });

const tooltip = document.getElementById("tooltip");

canvas.addEventListener("mousemove", e => {
    if (panning) { tooltip.style.display = "none"; return; }
    const g = hitTest(e.clientX, e.clientY);
    if (g != null) {
        const layout  = getLayout(currentIdx);
        const files   = groups[g].files;
        const lvl     = layout.level.get(g);
        const ins     = inEdges[g].size, outs = outEdges[g].size;
        const header  = files.length === 1 ? files[0] : `${files.length} files (SCC group)`;
        const fileList = files.length > 1
            ? "\n" + files.slice(0, 8).join("\n") + (files.length > 8 ? `\n  +${files.length - 8} more` : "")
            : "";
        const seFmt = groups[g].sideEffects ? "   side-effects: yes" : "";
        tooltip.textContent = `${header}${fileList}\nlevel: ${lvl}   importers: ${ins}   dependencies: ${outs}${seFmt}`;
        tooltip.style.display = "block";
        const tx = e.clientX + 14, ty = e.clientY + 10;
        tooltip.style.left = Math.min(tx, window.innerWidth  - tooltip.offsetWidth  - 8) + "px";
        tooltip.style.top  = Math.min(ty, window.innerHeight - tooltip.offsetHeight - 8) + "px";
    } else {
        tooltip.style.display = "none";
    }
});
canvas.addEventListener("mouseleave", () => { tooltip.style.display = "none"; });

// Click on node: highlight full transitive subtree + all indirect importers
// Click on background: clear
canvas.addEventListener("click", e => {
    if (didPan) return;
    const g = hitTest(e.clientX, e.clientY);
    if (g != null) {
        highlighted = { g, importers: transitiveImporters(g), dependencies: transitiveDeps(g) };
    } else {
        highlighted = null;
    }
    render();
});

window.addEventListener("resize", () => render());

// ── Legend ────────────────────────────────────────────────────────────────────

const legend = document.getElementById("legend");
for (const { color, label } of COLOR_MAP) {
    const entry  = document.createElement("div"); entry.className = "entry";
    const swatch = document.createElement("div"); swatch.className = "swatch";
    swatch.style.background = color;
    entry.append(swatch, document.createTextNode(label));
    legend.append(entry);
}
const defEntry  = document.createElement("div"); defEntry.className = "entry";
const defSwatch = document.createElement("div"); defSwatch.className = "swatch";
defSwatch.style.background = COLOR_DEFAULT;
defEntry.append(defSwatch, document.createTextNode("other"));
legend.append(defEntry);

const seEntry  = document.createElement("div"); seEntry.className = "entry";
const seSwatch = document.createElement("div"); seSwatch.className = "swatch";
seSwatch.style.background = "transparent";
seSwatch.style.border = "1.5px solid #f38ba8";
seEntry.append(seSwatch, document.createTextNode("side effects"));
legend.append(seEntry);

// ── Init ──────────────────────────────────────────────────────────────────────

resetTransform(getLayout(0));
buildTabs();
render();
