// generated by AI

/* eslint-disable @typescript-eslint/no-dynamic-delete */
import { readdirSync, writeFileSync, rmSync, mkdirSync, readFileSync } from "node:fs";
import { resolve, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname  = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT   = dirname(__dirname);

const ESM_DIR      = resolve(PKG_ROOT, "lib/esm");
const SRC_TRANS_DIR = resolve(PKG_ROOT, "src/translation");
const PKG_PATH     = resolve(PKG_ROOT, "package.json");

// ── Scan nls.messages.<lang>.js files ────────────────────────────────────────

const NLS_RE = /^nls\.messages\.(.+)\.js$/;

const locales = readdirSync(ESM_DIR)
    .map(f => NLS_RE.exec(f)?.[1])
    .filter((l): l is string => l != null)
    .sort();

console.log(`Found ${locales.length} translation locales: ${locales.join(", ")}`);

// ── Generate src/translation/<lang>.ts ───────────────────────────────────────

mkdirSync(SRC_TRANS_DIR, { recursive: true });

locales.push("en");

for (const locale of locales) {
    const name = locale === "en" ? "nls.messages.js" : `nls.messages.${locale}.js`;
    const source = readFileSync(join(ESM_DIR, name), "utf-8");

    let body = source
        .replace("globalThis._VSCODE_NLS_MESSAGES=", "const messages=")
        .replace("globalThis._VSCODE_NLS_LANGUAGE=", "const language=");

    if (locale === "en") {
        body += "\nconst language=undefined;";
    }

    writeFileSync(
        join(SRC_TRANS_DIR, `${locale}.ts`),
        `${body.trimEnd()}\nexport default { messages, language };\n`,
    );
}
console.log(`Generated ${locales.length} translation source files`);

// ── Remove stale src/translation/*.ts ────────────────────────────────────────

const localeSet = new Set(locales);
for (const entry of readdirSync(SRC_TRANS_DIR, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
    const name = entry.name.slice(0, -3);
    if (!localeSet.has(name)) {
        rmSync(join(SRC_TRANS_DIR, entry.name));
        console.log(`  Removed stale src/translation/${entry.name}`);
    }
}

// ── Update package.json exports ───────────────────────────────────────────────

const pkg = JSON.parse(readFileSync(PKG_PATH, "utf-8"));
const exports_: Record<string, unknown> = pkg.exports ?? {};

// Remove all existing ./translation-* entries
for (const key of Object.keys(exports_)) {
    if (key.startsWith("./translation-")) delete exports_[key];
}

// Add fresh entries for all scanned locales (sorted)
for (const locale of locales) {
    exports_[`./translation-${locale}`] = `./src/translation/${locale}.ts`;
}

pkg.exports = exports_;
writeFileSync(PKG_PATH, JSON.stringify(pkg, null, 4) + "\n");
console.log(`Updated package.json with ${locales.length} translation exports`);
