version: '3'

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true

tasks:
  install:
    desc: Install and copy original monaco-editor package
    cmds:
      - pnpm i
      - rm -rf monaco-editor lib
      - cp -R -L node_modules/monaco-editor .
      - mv monaco-editor lib
      - rm -rf lib/node_modules lib/min lib/dev
      - rm -f
          lib/package.json
          lib/esm/vs/editor/editor.all.js
          lib/esm/vs/editor/editor.api.js
          lib/esm/vs/editor/editor.api.d.ts
          lib/esm/vs/editor/editor.main.d.ts
          lib/esm/vs/editor/editor.main.js

  analyze:
    desc: Analyze monaco-editor package
    cmds:
      - bun dep-visualizer/analyze.ts

  patch-gen:
    desc: Apply patches to monaco-editor and generate source
    cmds:
      - task: install
      - task: ecma:config
      - bun scripts/patch.ts
      - task: patch-toml
      - bun scripts/gen-languages.ts
      - bun scripts/gen-translations.ts

  patch-toml:
    cmds:
      - mkdir -p lib/esm/vs/basic-languages/toml
      - rg '^import' lib/esm/vs/basic-languages/yaml/yaml.js --no-line-number > lib/esm/vs/basic-languages/toml/toml.js
      - cat patches/toml/toml.js >> lib/esm/vs/basic-languages/toml/toml.js
      - rg '^export' lib/esm/vs/basic-languages/yaml/yaml.js --no-line-number >> lib/esm/vs/basic-languages/toml/toml.js
      - cp patches/toml/toml.contribution.js lib/esm/vs/basic-languages/toml

  check:
    - task: ecma:check
  fix:
    - task: ecma:fix
    

  build:
    - task: patch-gen
    - task: ecma:lib-build
    - task: build-dts
    # remove extra files
    - rm -f lib/CHANGELOG.md lib/README.md lib/monaco.d.ts

  build-dts:
    # fix dts files
    - for file in dist/_dts_/src/language/*.d.ts; do
        echo 'export {}' > $file;
      done
    - rm -f dist/_dts_/src/language/*.d.ts.map
    - for file in dist/_dts_/src/language-ex/*.d.ts; do
        echo 'export {}' > $file;
      done
    - rm -f dist/_dts_/src/language-ex/*.d.ts.map
    - for file in dist/_dts_/src/translation/*.d.ts; do
        echo 'export {}' > $file;
      done
    - rm -f dist/_dts_/src/translation/*.d.ts.map
    - for file in dist/_dts_/src/worker/*.d.ts; do
        echo 'export {}' > $file;
      done
    - rm -f dist/_dts_/src/worker/*.d.ts.map
    - cat lib/monaco.d.ts > dist/_dts_/src/core.d.ts
    - rm -f dist/_dts_/src/core.d.ts
