version: '3'

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true

tasks:
  build:
    - task: ecma:doc-build

  dev:
    - task: ecma:doc-dev
