name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check & Build
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          mono-dev: false
          ecma-pnpm: true
      - run: pnpm install
      - run: task check
      - run: task build
